### ISSUE TITLE
Error in Explore Page

### ISSUE THREAD

**Issue by Sid72020123** [Looky1173/Itinerary#13]
When I go to explore page and see the "Jams per page" and set it to "3" and go till the last page "4":
![image](https://user-images.githubusercontent.com/70252606/155316753-0f466f5b-de52-4614-af2b-d8948918e051.png)
It shows "page 4 of 4"

And when I change the "Jams per page " to 20 without changing the page number, I get:
![image](https://user-images.githubusercontent.com/70252606/155316966-8d891db7-f1f6-4b6c-ab63-b1af238ddd2a.png)
It says "Page 4 of 1"

I hope that this info helps to fix this bug.

**Comment by AnAlgorithm** [comment]
Great Catch.

**Comment by Sid72020123** [comment]
Thank you!

**Comment by AnAlgorithm** [comment]
@Sid72020123 no problem. Let's see what @Looky1173 says.

**Comment by Sid72020123** [comment]
Ok

**Comment by Sid72020123** [comment]
Best of Luck with solving this bug!

**Comment by Looky1173** [comment]
This bug was fixed in #13.

**Comment by Sid72020123** [comment]
Cool!
