### ISSUE TITLE
does anyone know where the code for adding admins?

### ISSUE THREAD

**Issue by PoIygon** [Looky1173/Itinerary#16]
im gonna try to commit so i can get admin

**Comment by Looky1173** [comment]
The code for updating users, including admin roles, is [here](https://github.com/Looky1173/Itinerary/blob/2275acbbc48c19d998eefc5cf6044fcecfc390ac/components/UsersEditorModal.vue#L47-L86). However, if you have a development MongoDB server running locally, you can just add `admin: true` to user documents.

**Comment by Looky1173** [comment]
Also, [here is how the backend handles updating users](https://github.com/Looky1173/Itinerary-Server/blob/5bd1dc67e840bc144f857a6181c3ec79f77e3df5/index.js#L112-L190).
