### ISSUE TITLE
Dev page doesn't work.

### ISSUE THREAD

**Issue by jammerpop13o** [Looky1173/Itinerary#19]
Redirects to page doesn't exist screen. (your website's doesn't exist screen, obviously.)

**Comment by Looky1173** [comment]
Yes, the _Developer_ page doesn't exist yet. I'm currently working on Incubator, the successor of Itinerary. When I finish it, I could take a look at patching up Itinerary, but I won't be adding any new features to the platform.

**Comment by jammerpop13o** [comment]
closed cuz answered
