### ISSUE TITLE
Every modal has a random scrollbar that does nothing

### ISSUE THREAD

**Issue by kccuber-scratch** [Looky1173/Itinerary#2]
![image](https://user-images.githubusercontent.com/92891642/153765267-323626fb-7fd4-4772-8de0-d6fe038a28a3.png)
See that scrollbar? This should be an easy fix with 
```css
overflow-y: hidden
```

**Comment by Looky1173** [comment]
Thanks for reporting the problem! This was addressed in 3df12a4670368537f55b24ed06ad0bc67b1bf949, closing.
