### ISSUE TITLE
Cannot login from Itinerary.

### ISSUE THREAD

**Issue by WojtekCodesToday** [Looky1173/Itinerary#24]
I logged in from Ocular and it went fine, when i tried with **this** website (Itinerary) there was a timeout when used the options to log in.

**Comment by Adzboy** [comment]
I'm also struggling, it's working fine for other verification systems using Scratch Auth so it must be a problem with Itinerary specifically. Cloudflare suggests an issue with the host.

**Comment by Adzboy** [comment]
@Looky1173 can you take a look?

**Comment by Looky1173** [comment]
Apologies for the long wait, the issue is now resolved! Moreover, profile pictures are back and submitting projects is no longer broken.
