### ISSUE TITLE
Issue in Edit Game Jam popup

### ISSUE THREAD

**Issue by AnAlgorithm** [Looky1173/Itinerary#4]
In the "Edit this Game Jam" popup, the bottom of the buttons ```update game jam``` and ```discard edits``` go below the taskbar. In fullscreen view however, this becomes normal.
![Itinerary - Google Chrome 15-02-2022 14_40_07](https://user-images.githubusercontent.com/64064699/154029709-de5c8354-c9ca-4d41-90d8-3faa3357fea2.png)

**Comment by Looky1173** [comment]
@AnAlgorithm Great catch, thanks for reporting! Fixed in 329666ff03573d459eb5a7c735f3d81bec097302, closing.
