### ISSUE TITLE
Button is too large

### ISSUE THREAD

**Issue by AnAlgorithm** [Looky1173/Itinerary#5]
![Itinerary - Google Chrome 17-02-2022 09_48_33](https://user-images.githubusercontent.com/64064699/154404516-08f4f525-3c85-4cb5-980d-8f1388f65248.png)
The [⁝] button looks a bit too large here. I went to the inspect element and found:
```css

padding: .5rem 1rem;
``` 
Consider changing that to:
```css

padding: .5rem;
```

**Comment by AnAlgorithm** [comment]
> The problem is that removing that extra `1rem` horizontal padding would cause the button to be very thin and difficult to click, especially on mobile devices. Therefore, I think that this padding is indeed necessary for accessibility reasons. ![image](https://user-images.githubusercontent.com/60521810/154710953-bb64ca53-84f5-42aa-88fb-f3b91584d2b2.png)
Would it be possible to have it like it is thin on big screens but goes back to 1rem on smaller screens?

**Comment by Looky1173** [comment]
@

**Comment by Looky1173** [comment]
@AnAlgorithm I am going to ask the community what they think!

**Comment by AnAlgorithm** [comment]
> @AnAlgorithm I am going to ask the community what they think!

ok

**Comment by mxmou** [comment]
A square button would look good and probably still be easy to click.

**Comment by Looky1173** [comment]
> A square button would look good and probably still be easy to click.

I can't make the [⁝] button squared without messing with the shape of its neighbouring submit button but I could remove the extra padding on larger screens (ex. >720px).

**Comment by Looky1173** [comment]
528e74b139d0dcdbc4c0a8687bcb1bf44841c9bf should make the [⁝] button thinner on wider screens. Let me know what you think!

**Comment by AnAlgorithm** [comment]
> > A square button would look good and probably still be easy to click.
> 
> I can't make the [⁝] button squared without messing with the shape of its neighbouring submit button but I could remove the extra padding on larger screens (ex. >720px).

perfect

> 528e74b should make the [⁝] button thinner on wider screens. Let me know what you think!

looks good! Thanks!

**Comment by AnAlgorithm** [comment]
I think we should close this as it is resolved.

**Comment by PoIygon** [comment]
I feel like the button should be bigger and say “options”

**Comment by AnAlgorithm** [comment]
> I feel like the button should be bigger and say “options”

I feel that's unnecessary. The [:] button already means options, and there's no point in making it bigger. A small [:] button is quite enough. Let's hear what @Looky1173 has to say, though.

**Comment by Looky1173** [comment]
> I feel like the button should be bigger and say “options”

I agree with @AnAlgorithm that this wouldn’t be necessary. Implementing this would also mean squashing the submission button and that wouldn’t look very nice. Nevertheless, I could add a tooltip “Options” to make the role of the [:] button more obvious. What do you think @PoIygon?

**Comment by Mbrick2** [comment]
I agree with @Looky1173

**Comment by Venatus123** [comment]
square looks pretty good

**Comment by Looky1173** [comment]
I've added a temporary tooltip until we come up with something better:
![image](https://user-images.githubusercontent.com/60521810/154843219-1fe0582b-69e8-413c-855d-96de7104867d.png)

**Comment by AnAlgorithm** [comment]
@Looky1173 cool! seems good

**Comment by Looky1173** [comment]
> I just realised that if you hover DIRECTLY over the three dots icon it shows "3-vertical-dots" in the tooltip instead of "options"

@AnAlgorithm Fixed in ec23cd32669a39a64b56e83fc7c3a85d338c01e1.

**Comment by AnAlgorithm** [comment]
@Looky1173 Cool!
